version: '3'

services:
  dynamo-db:
    container_name: dynamo-db
    image: amazon/dynamodb-local
    ports:
      - '8000:8000'
    working_dir: /home/dynamodblocal
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"